# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# Network Settings
#
hostname: {%= hostname %}
ip: {%= ip %}

#
# WordPress Settings
#
version: {%= wp_version %}
lang: {%= wp_lang %}
